#!/usr/bin/env bash
# Bash script that will display information about subdomains.

get_subdomain_info() {
    domain="$1"
    subdomain="$2"

    info=$(dig "$subdomain"."$domain" +answer | grep -A1 'ANSWER SECTION:')

    RECORD_TYPE=$(echo "$info" | awk 'NR==2{print $4}')
    DESTINATION=$(echo "$info" | awk 'NR==2{print $5}')

    echo "The subdomain $subdomain is a $RECORD_TYPE record and points to $DESTINATION"
}

display_subdomains() {
    domain="$1"
    get_subdomain_info "$domain" www
    get_subdomain_info "$domain" lb-01
    get_subdomain_info "$domain" web-01
    get_subdomain_info "$domain" web-02
}

if [ $# -eq 1 ]; then
    display_subdomains "$1"
elif [ $# -eq 2 ]; then
    get_subdomain_info "$1" "$2"
fi
