#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server:

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer file using SCP to the server's home directory
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$ubuntu"@"$54.237.88.88":~