#!/usr/bin/env bash
#Configuring Nginx server to have a custom 404 page with particular strin

#step 1
sudo apt update
sudo apt install nginx -y

#step 2
sudo sed -i 's/listen [::]:80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

cat <<EOF > /var/www/html/error-page.html
Ceci n'est pas une page
EOF

#step3
sudo bash -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    error_page 404 /error-page.html;
    location /error-page.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default'


#last step
sudo service nginx restart

