#!/usr/bin/env bash
#Write a Bash script that displays a list of currently running processes.
#Requirements:
#Must show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy
echo "PID PPID TTY CMD" #this display headers for the output
#ps command list all proccess for the requirement
ps aux --forest
