#!/usr/bin/env bash
#Write a Bash script that displays the PID, along with the process name, 
#of processes whose name contain the word bash.
#Requirements:
#You cannot use ps
pids=$(pgrep -f bash) #use pgrep to find the PIDs of processes containg bash
for pid in $pids #iterate through pid and display their corresponding name
do
    process_name=$(ps -o comm= -p "$pid")
    echo "$pid $process_name"
done
