#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#Requirements:
#You must use the while loop
hour=0
minute=1
while [ $hour -le 12 ]; do
    echo "Hour : $hour"
    while [ $minute -le 59 ]; do
            echo $minute
            minute=$((minute + 1))
    done
    minute=0 #resetting minute to 0
    hour=$((hour + 1))
done